# Generated by Django 5.1.6 on 2025-02-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_item_item_image_alter_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(blank=True, default='supernova.jpg', upload_to=''),
        ),
    ]
