# Generated by Django 5.1.6 on 2025-02-25 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_item_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_image',
        ),
    ]
