# Generated by Django 5.1.6 on 2025-02-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_item_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='has_meat_options',
            field=models.BooleanField(default=True),
        ),
    ]
