# Generated by Django 5.1.6 on 2025-02-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_item_has_meat_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customization',
            old_name='spice_level',
            new_name='spicy_level',
        ),
        migrations.AddField(
            model_name='item',
            name='has_spicy_options',
            field=models.BooleanField(default=True),
        ),
    ]
