# Generated by Django 5.1.6 on 2025-02-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_rename_spice_level_customization_spicy_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customization',
            name='spicy_level',
            field=models.CharField(choices=[('Mild', 'Mild'), ('Medium', 'Medium'), ('High', 'High')], max_length=50),
        ),
    ]
