# Generated by Django 5.1.6 on 2025-03-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_customization_spicy_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cate_image',
            field=models.ImageField(blank=True, default='taddib-icon.jpeg', upload_to=''),
        ),
    ]
