# Generated by Django 5.1.6 on 2025-03-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_category_cate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customization',
            name='meat',
            field=models.CharField(blank=True, choices=[('Beef', 'Beef'), ('Chicken', 'Chicken')], max_length=50, null=True),
        ),
    ]
