# Generated by Django 5.1.7 on 2025-03-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_customization_meat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='is_available',
            new_name='availability',
        ),
        migrations.AddField(
            model_name='table',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
