# Generated by Django 5.1.7 on 2025-03-20 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeatOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('extra_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='SpicyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Label for the spiciness level (e.g., Mild, Medium, Hot)', max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_image',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='has_meat_options',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='has_spicy_options',
            field=models.BooleanField(default=False),
        ),
    ]
