# Generated by Django 5.1.7 on 2025-03-20 14:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_meatoption_spicylevel_remove_item_item_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='customization',
        ),
        migrations.RemoveField(
            model_name='userorder',
            name='table',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user_order',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=50)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.table')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order.order'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='order.item')),
                ('meat_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.meatoption')),
                ('spicy_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.spicylevel')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.selection'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Customization',
        ),
        migrations.DeleteModel(
            name='UserOrder',
        ),
    ]
