# Generated by Django 5.1.7 on 2025-03-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_alter_orderitem_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='create a qr code everytime a table is saved!', null=True, upload_to='qrcodes/'),
        ),
    ]
