# Generated by Django 5.1.7 on 2025-04-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_alter_table_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bar_status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Preparing', 'Preparing')], default='Waiting', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='kitchen_status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Preparing', 'Preparing')], default='Waiting', max_length=50),
        ),
    ]
