# Generated by Django 5.1.7 on 2025-04-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_order_bar_status_order_kitchen_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bar_status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Preparing', 'Preparing'), ('Ready', 'Ready')], default='Waiting', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='kitchen_status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Preparing', 'Preparing'), ('Ready', 'Ready')], default='Waiting', max_length=50),
        ),
    ]
